// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuwyUqaXyDU2ar0jCObazT34GTsNucWlw',
    appId: '1:980067983543:web:a18ab6518bd0b49a0dad32',
    messagingSenderId: '980067983543',
    projectId: 'alacancha-96ac1',
    authDomain: 'alacancha-96ac1.firebaseapp.com',
    storageBucket: 'alacancha-96ac1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH92wGnVdESANEIyWI7pBNE_Hn4Ntvxrg',
    appId: '1:980067983543:android:be324a3a7ff98cc10dad32',
    messagingSenderId: '980067983543',
    projectId: 'alacancha-96ac1',
    storageBucket: 'alacancha-96ac1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-jJGnGl6s7Ob1cEFumIeZDH6oIq3pP-g',
    appId: '1:980067983543:ios:ab96009590953fc40dad32',
    messagingSenderId: '980067983543',
    projectId: 'alacancha-96ac1',
    storageBucket: 'alacancha-96ac1.firebasestorage.app',
    iosClientId: '980067983543-ea2m1gsc53m48uda6c8qnp82pea7psbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.alacanchaAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-jJGnGl6s7Ob1cEFumIeZDH6oIq3pP-g',
    appId: '1:980067983543:ios:ab96009590953fc40dad32',
    messagingSenderId: '980067983543',
    projectId: 'alacancha-96ac1',
    storageBucket: 'alacancha-96ac1.firebasestorage.app',
    iosClientId: '980067983543-ea2m1gsc53m48uda6c8qnp82pea7psbt.apps.googleusercontent.com',
    iosBundleId: 'com.example.alacanchaAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuwyUqaXyDU2ar0jCObazT34GTsNucWlw',
    appId: '1:980067983543:web:556e11f0341a3c3d0dad32',
    messagingSenderId: '980067983543',
    projectId: 'alacancha-96ac1',
    authDomain: 'alacancha-96ac1.firebaseapp.com',
    storageBucket: 'alacancha-96ac1.firebasestorage.app',
  );
}
